//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Career
    {
        public int CareerID { get; set; }
        public Nullable<int> OrganizationID { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public Nullable<bool> IsCurrent { get; set; }
        public Nullable<int> UserID { get; set; }
        public string Designation { get; set; }
    
        public virtual Organization Organization { get; set; }
        public virtual UserInfo UserInfo { get; set; }
    }
}
