//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repo
{
    using System;
    using System.Collections.Generic;
    
    public partial class CourseResult
    {
        public Nullable<int> SubjectID { get; set; }
        public Nullable<int> ExamineeID { get; set; }
        public Nullable<int> MarksObtained { get; set; }
        public int CourseResultID { get; set; }
    
        public virtual Subject Subject { get; set; }
        public virtual UserInfo UserInfo { get; set; }
    }
}
