//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repo
{
    using System;
    using System.Collections.Generic;
    
    public partial class EventAnswer
    {
        public int EventAnswerID { get; set; }
        public Nullable<int> EventID { get; set; }
        public Nullable<int> QuestionID { get; set; }
        public Nullable<int> ExamineeID { get; set; }
        public string SubmittedAnswer { get; set; }
        public string AnswerReviewText { get; set; }
        public string AnswerReviewImage { get; set; }
        public Nullable<int> MarksObtained { get; set; }
    
        public virtual Event Event { get; set; }
        public virtual Question Question { get; set; }
        public virtual UserInfo UserInfo { get; set; }
    }
}
