//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repo
{
    using System;
    using System.Collections.Generic;
    
    public partial class EventQuestion
    {
        public int EventID { get; set; }
        public int QuestionID { get; set; }
        public Nullable<int> Marks { get; set; }
    
        public virtual Event Event { get; set; }
        public virtual Question Question { get; set; }
    }
}
