//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repo
{
    using System;
    using System.Collections.Generic;
    
    public partial class EventInvitation
    {
        public int EventInvitaionID { get; set; }
        public Nullable<int> InvitedUser { get; set; }
        public string Code { get; set; }
        public Nullable<int> EventInvitationStatusID { get; set; }
        public Nullable<int> EventID { get; set; }
    
        public virtual Event Event { get; set; }
        public virtual EventInvitationStatu EventInvitationStatu { get; set; }
        public virtual UserInfo UserInfo { get; set; }
    }
}
