//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Event
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Event()
        {
            this.EventAnswers = new HashSet<EventAnswer>();
            this.EventInvitations = new HashSet<EventInvitation>();
            this.EventQuestions = new HashSet<EventQuestion>();
            this.EventRegistrations = new HashSet<EventRegistration>();
            this.EventReports = new HashSet<EventReport>();
            this.Results = new HashSet<Result>();
            this.Subjects = new HashSet<Subject>();
        }
    
        public int EventID { get; set; }
        public string EventName { get; set; }
        public Nullable<int> HostID { get; set; }
        public Nullable<System.DateTime> StartTime { get; set; }
        public Nullable<System.DateTime> EndTime { get; set; }
        public Nullable<int> EventTypeID { get; set; }
        public Nullable<int> EventStatusID { get; set; }
        public bool IsPublic { get; set; }
        public Nullable<int> InstitutionCategoryID { get; set; }
        public Nullable<int> TotalMarks { get; set; }
        public Nullable<int> PerEasyQuestionMarks { get; set; }
        public Nullable<int> PerMediumQuestionMarks { get; set; }
        public Nullable<int> PerHardQuestionMarks { get; set; }
    
        public virtual EventStatu EventStatu { get; set; }
        public virtual EventType EventType { get; set; }
        public virtual InstitutionCategory InstitutionCategory { get; set; }
        public virtual UserInfo UserInfo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EventAnswer> EventAnswers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EventInvitation> EventInvitations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EventQuestion> EventQuestions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EventRegistration> EventRegistrations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EventReport> EventReports { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Result> Results { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Subject> Subjects { get; set; }
    }
}
