//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Question
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Question()
        {
            this.EventAnswers = new HashSet<EventAnswer>();
            this.EventQuestions = new HashSet<EventQuestion>();
            this.EventReports = new HashSet<EventReport>();
            this.QuestionOptions = new HashSet<QuestionOption>();
        }
    
        public int QuestionID { get; set; }
        public string QuestionText { get; set; }
        public Nullable<int> QuestionDifficultyID { get; set; }
        public string QuestionAnswer { get; set; }
        public Nullable<int> QuestionTypeID { get; set; }
        public string QuestionChapterName { get; set; }
        public Nullable<int> QuestionSubjectID { get; set; }
        public string QuestionSolutionText { get; set; }
        public string QuestionSolutionImage { get; set; }
        public Nullable<int> QuestionRepositoryID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EventAnswer> EventAnswers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EventQuestion> EventQuestions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EventReport> EventReports { get; set; }
        public virtual QuestionDifficulty QuestionDifficulty { get; set; }
        public virtual QuestionBank QuestionBank { get; set; }
        public virtual QuestionSubject QuestionSubject { get; set; }
        public virtual QuestionType QuestionType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<QuestionOption> QuestionOptions { get; set; }
    }
}
