//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repo
{
    using System;
    using System.Collections.Generic;
    
    public partial class QuestionBank
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public QuestionBank()
        {
            this.Questions = new HashSet<Question>();
        }
    
        public int QuestionBankID { get; set; }
        public string QuestionBankName { get; set; }
        public Nullable<int> InstitutionCategoryID { get; set; }
        public Nullable<int> OwnerID { get; set; }
        public bool IsPublic { get; set; }
    
        public virtual InstitutionCategory InstitutionCategory { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Question> Questions { get; set; }
        public virtual UserInfo UserInfo { get; set; }
    }
}
