//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repo
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ScholarHackDBContext : DbContext
    {
        public ScholarHackDBContext()
            : base("name=ScholarHackDBContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AccountType> AccountTypes { get; set; }
        public virtual DbSet<Career> Careers { get; set; }
        public virtual DbSet<CourseResult> CourseResults { get; set; }
        public virtual DbSet<EducationalHistory> EducationalHistories { get; set; }
        public virtual DbSet<Event> Events { get; set; }
        public virtual DbSet<EventAnswer> EventAnswers { get; set; }
        public virtual DbSet<EventInvitation> EventInvitations { get; set; }
        public virtual DbSet<EventInvitationStatu> EventInvitationStatus { get; set; }
        public virtual DbSet<EventQuestion> EventQuestions { get; set; }
        public virtual DbSet<EventRegistration> EventRegistrations { get; set; }
        public virtual DbSet<EventRegistrationStatu> EventRegistrationStatus { get; set; }
        public virtual DbSet<EventReport> EventReports { get; set; }
        public virtual DbSet<EventStatu> EventStatus { get; set; }
        public virtual DbSet<EventType> EventTypes { get; set; }
        public virtual DbSet<Institution> Institutions { get; set; }
        public virtual DbSet<InstitutionCategory> InstitutionCategories { get; set; }
        public virtual DbSet<InstitutionCategoryType> InstitutionCategoryTypes { get; set; }
        public virtual DbSet<Organization> Organizations { get; set; }
        public virtual DbSet<Question> Questions { get; set; }
        public virtual DbSet<QuestionDifficulty> QuestionDifficulties { get; set; }
        public virtual DbSet<QuestionOption> QuestionOptions { get; set; }
        public virtual DbSet<QuestionRepository> QuestionRepositories { get; set; }
        public virtual DbSet<QuestionSubject> QuestionSubjects { get; set; }
        public virtual DbSet<QuestionType> QuestionTypes { get; set; }
        public virtual DbSet<Result> Results { get; set; }
        public virtual DbSet<Subject> Subjects { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<UserInfo> UserInfoes { get; set; }
        public virtual DbSet<UserStatu> UserStatus { get; set; }
        public virtual DbSet<UserType> UserTypes { get; set; }
        public virtual DbSet<SystemConfig> SystemConfigs { get; set; }
    }
}
