//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repo
{
    using System;
    using System.Collections.Generic;
    
    public partial class SystemConfig
    {
        public double AvgParticipantsPerEvent { get; set; }
        public double AvgResultPerEvent { get; set; }
        public Nullable<int> PerEasyQuestionMarks { get; set; }
        public Nullable<int> PerMediumQuestionMarks { get; set; }
        public Nullable<int> PerHardQuestionMarks { get; set; }
    }
}
